start: NAME constants module labels

constants: constant*
constant: "const" "int" NAME "=" INT ";"

module: "module" NAME vars commands "endmodule"

vars: var*
var: NAME ":" "[" expr ".." expr "]" ";"

commands: command*
command: "[]" guards "->" branches ";"

guards: bool_term ("&" bool_term)*

branches: branch ("+" branch)*

branch: expr ":" updates

updates: update ("&" update)*
update: "(" VAR "'" "=" expr ")"

labels: label*
label: "label" "\"" NAME "\"" "=" guards ";"

?bool_term: expr "<" expr            -> lt
          | expr "=" expr            -> eq
          | expr

?expr: expr "+" term   -> add
     | expr "-" term   -> sub
     | term

?term: term "*" factor -> mul
     | term "/" factor -> div
     | factor

?factor: INT
       | VAR
       | "(" expr ")"

VAR: NAME   // Var becomes a z3 int whereas name becomes a str

%import common.CNAME -> NAME
%import common.NUMBER
%import common.INT
%import common.ESCAPED_STRING -> STRING
%import common.NEWLINE
%import common.WS_INLINE

// ----------------------
// Comment support
// ----------------------

// Single-line comments (C++ / Java style)
COMMENT_SINGLE: /\/\/[^\n]*/

// Multi-line comments (C style)
COMMENT_MULTI: /\/\*[\s\S]*?\*\//

%ignore COMMENT_SINGLE
%ignore COMMENT_MULTI

%ignore WS_INLINE
%ignore NEWLINE